#!/bin/sh -e
#
# Usage:
#    rdfcache [-login=user -pswd=password] [-cache=CacheDirectory -ruleset=Ruleset] [-notimport=notimportfile] [-sesame=serverURL -repository=repositoryID] \
#       [-dropChoice=flushRepositoryOnDrop/dropWithMemoryStore/dropWithMemoryStoreDeleteRepository] [-xmlfromhttp=true/false] [-loadfromtrig=fullpatthtothetrigfile] \
#       [-construct=fileofconstructrule] [-constructoutput=fullpatthtothefileholdsconstructruleresults] config_files/owl_files 
#
# Example:
#    rdfcache -cache=dlmetadatatest -notimport=urltoskip-dl.txt -dropChoice=dropWithMemoryStoreDeleteRepository http://iridl.ldeo.columbia.edu/ontologies/iridlmetadata.owl >dl.log
#
bindir=$(dirname "$0")
libdir="$bindir/../lib"
#JAVAOPTS=${JAVAOPTS:--Xmx2048m}

exec java $JAVAOPTS -cp "$libdir/*" iri.semantics.GenerateNTriples "$@"
